#
# EvoPPI Docker
#
# Copyright (C) 2017-2018 - Noé Vázquez González,
# Miguel Reboiro-Jato, Jorge Vieira, Hugo López-Fernández,
# and Cristina Vieira.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

version: '3.4'
services:
  database:
    build:
      context: .
      dockerfile: docker/Dockerfile.database
      args:
        version: ${EVOPPI_DATABASE_VERSION:-1.0.0}
        admin_password: ${EVOPPI_DATABASE_ADMIN_PASSWORD:-admin}
        researcher_password: ${EVOPPI_DATABASE_RESEARCHER_PASSWORD:-researcher}
    container_name: evoppi-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "evoppipass"
      MYSQL_DATABASE: "evoppi"
      MYSQL_USER: "evoppi"
      MYSQL_PASSWORD: "evoppipass"
    volumes:
      - evoppi-database-data:/var/lib/mysql
    networks:
      evoppi-network:
        ipv4_address: 172.30.0.10
    command: --wait_timeout=28800 --max_allowed_packet=1G
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
      args:
        backend_host: ${EVOPPI_BACKEND_HOST:-localhost:8080}
        version: ${EVOPPI_BACKEND_VERSION:-1.2.0}
        buildear: ${EVOPPI_BACKEND_EAR_BUILD:-1.2.0}
    container_name: evoppi-backend
    ports:
      - "${EVOPPI_BACKEND_HTTP_PORT:-8080}:8080"
      - "${EVOPPI_BACKEND_AJP_PORT:-8009}:8009"
      - "${EVOPPI_BACKEND_HTTP_MANAGEMENT_PORT:-9990}:9990"
    restart: always
    privileged: true
    depends_on:
      - database
    volumes:
      - "${TEMP_DATA_DIRECTORY:-/tmp/evoppi-docker}:${TEMP_DATA_DIRECTORY:-/tmp/evoppi-docker}"
    environment:
      TEMP_DATA_DIRECTORY: "${TEMP_DATA_DIRECTORY:-/tmp/evoppi-docker}"
    networks:
      evoppi-network:
        ipv4_address: 172.30.0.20
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        frontend_host: ${EVOPPI_FRONTEND_HOST:-localhost}
        backend_host: ${EVOPPI_BACKEND_HOST:-localhost:8080}
        version: ${EVOPPI_FRONTEND_VERSION:-1.2.0}        
    container_name: evoppi-frontend
    ports:
      - "${EVOPPI_FRONTEND_HTTP_PORT:-80}:80"
    restart: always
    depends_on:
      - database
      - backend
    networks:
      evoppi-network:
        ipv4_address: 172.30.0.30
volumes:
  evoppi-database-data:
networks:
  evoppi-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/16
